# *******************************************************************************
# * Copyright (C) 2017-2023 German Aerospace Center (DLR). 
# * Eclipse ADORe, Automated Driving Open Research https://eclipse.org/adore
# *
# * This program and the accompanying materials are made available under the 
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0.
# *
# * SPDX-License-Identifier: EPL-2.0 
# *
# * Contributors: 
# * Matthias Nichting
# ********************************************************************************

float64 a
float64 b
float64 c
float64 d
float64 m
float64 width

bool a_valid
bool b_valid
bool c_valid
bool d_valid
bool m_valid
bool width_valid